services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - ALLOWED_HOSTS=*
    volumes:
      - ./media:/app/media
      - ./migration_script.sh:/app/migration_script.sh
    command: >
      bash -c "
        chmod +x /app/migration_script.sh &&
        /app/migration_script.sh &&
        daphne -b 0.0.0.0 -p 8000 naan_mudhalvan_monolith.asgi:application
      "

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=naan_mudhalvan

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: