services:
  - type: web
    name: naan-mudhalvan-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: DEBUG
        value: 0
      - key: ALLOWED_HOSTS
        value: "*"
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        sync: false
      - key: POSTGRES_DB
        value: naan_mudhalvan
      - key: POSTGRES_HOST
        value: db
    dockerContext: .